Repository jeedom/core, pull requests merged in 2024-05, with the labels that each got.

#2588 Update plan.js
  desktop/js/plan.js
Labels: bug

#2591 fix #2590
  core/class/system.class.php
Labels: bug, Need approval

#2601 Proposition de fix battery page
  core/class/eqLogic.class.php
  desktop/css/desktop.main.css
Labels: Ready to merge

#2604 Move to beta
  .github/pull_request_template.md
  CONTRIBUTING.md
  core/class/eqLogic.class.php
  core/class/system.class.php
  core/config/version
  core/js/cmd.class.js
  core/js/eqLogic.class.js
  core/repo/market.repo.php
  core/themes/core2019_Light/desktop/colors.css
  desktop/common/js/utils.js
  desktop/css/coreWidgets.css
  desktop/css/desktop.main.css
  desktop/js/log.js
  desktop/js/plan.js
  desktop/js/timeline.js
  desktop/js/update.js
  desktop/js/user.js
  desktop/php/log.php
  desktop/php/plugin.php
  desktop/php/update.php
  docs/fr_FR/changelog.md
  install/OS_specific/Docker/init.sh
Labels: Need approval

#2620 feat: Add fail2ban status in health
  core/class/jeedom.class.php
Labels: Enhancement, Need approval

#2619 fix: Health misaligned
  desktop/php/health.php
Labels: Enhancement

#2618 fix: network::test() takes to much time to fail
  core/class/network.class.php
Labels: Need approval

#2570 Clean useless code line
  install/backup.php
Labels: Need approval

#2605 read a widget optional parameter with " fix
  desktop/modal/cmd.configure.php
  desktop/modal/eqLogic.configure.php
  desktop/modal/eqLogic.dashboard.edit.php
Labels: Need approval
