Repository jeedom/core, pull requests merged in 2024-03, with the labels that each got.

#2424 auto switch to light theme if legacy
  core/class/jeedom.class.php
  docs/fr_FR/changelog.md
Labels: Need approval

#2421 Freez 4.4 Version
  core/api/jeeApi.php
  core/class/cache.class.php
  core/class/cmd.class.php
  core/class/config.class.php
  core/class/eqLogic.class.php
  core/class/jeedom.class.php
  core/class/plugin.class.php
  core/class/scenario.class.php
  core/class/scenarioExpression.class.php
  core/js/cmd.class.js
  core/repo/market.display.repo.php
  core/template/dashboard/cmd.info.string.color.html
  core/template/mobile/cmd.info.string.color.html
  core/template/mobile/cmd.info.string.tile.html
  desktop/css/coreWidgets.css
  desktop/css/desktop.main.css
  desktop/css/dom.ui.css
  desktop/js/history.js
  desktop/php/administration.php
  desktop/php/index.php
  docs/fr_FR/changelog.md
  mobile/css/coreWidgets.css
Labels: Freeze Version

#2441 fix domUtils.ajax onError
  core/dom/dom.utils.js
Labels: bug
